config/routes.rb
MountaineeringWebsite::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'static_pages#home'
  get "/expeditions" => 'static_pages#expeditions'
  get "/about" => 'static_pages#about'
  get "/roadmap" => 'static_pages#roadmap'
  get "/worldmap" => 'static_pages#worldmap'
  get "/fundraising" => 'static_pages#fundraising'
  resources :photos
  resources :posts

  devise_for :users

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	has_attached_file :attachment
	validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
	include ActionView::Helpers::SanitizeHelper
  acts_as_taggable

	def content
		sanitize read_attribute(:content), attributes: %w(href style src)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  respond_to :html,:json

  def index
    @photos = Photo.all
    respond_with(@photos)
  end

  def show
    respond_with(@photo)
  end

  def new
    @photo = Photo.new
    respond_with(@photo)
  end

  def edit
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.save
    respond_to do |format|
      format.html
      format.json { render json: {photo_url: @photo.attachment.url} }
    end
  end

  def update
    @photo.update(photo_params)
    respond_with(@photo)
  end

  def destroy
    @photo.destroy
    respond_with(@photo)
  end

  private
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:caption, :attachment)
    end
end

app/controllers/posts_controller.rb
include PostsHelper
class PostsController < ApplicationController
  before_action :is_admin?, only: [:new, :edit, :update, :destroy]
  respond_to :html

  def index
    @posts = Post.order("created_at DESC")
    @posts = @posts.tagged_with(params[:tag]) if params[:tag]
    respond_with(@posts)
  end

  def show
    @post = Post.find(params[:id])
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def expeditions
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def is_admin?
	  if current_user && current_user.admin?
	    true
	  else
	    render :text => 'Admins only :)'
	  end
	end

	def get_first_image(content)
		doc = Nokogiri::HTML( content )
		img_srcs = doc.css('img').map{ |i| i['src'] }
		return img_srcs[0]
	end
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/application/home.html.erb
lol

app/views/layouts/_footer.html.erb
<footer>
	<div class="row">
		<div class="col-lg-12">
			<p>Copyright &copy; SUTD Mountaineering 2016</p>
		</div>
	</div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">SUTD Mountaineering</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "World Map", worldmap_path %></li>
                <li><%= link_to "Road Map", roadmap_path %></li>
                <li><%= link_to "Fundraising", fundraising_path %></li>
                <li><%= link_to "Blog", posts_path %></li>
                <!-- Leaving this out until we do the tagging thing. -->
                <!-- <li><%= link_to "Expeditions", expeditions_path %></li> -->
                <!-- Leaving this out for now -->
                <!-- <li><%= link_to "Equipment", "#" %></li> -->
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUTD Mountaineering</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render partial: "layouts/navbar" %>
	<% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "flash #{key}" %>
	<% end %>
	<%= yield %>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<%= render partial: "layouts/footer" %>
		</div>
		<div class="col-md-2"></div>
	</div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MountaineeringWebsite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render partial: "layouts/navbar" %>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
      	<div class="border-form-div">
      	<%= yield %>
      	</div>
      </div>
    </div>	
</body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo, html: { multipart: true } do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
    <%= f.file_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <thead>
    <tr>
      <th>Caption</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.caption %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Caption:</strong>
  <%= image_tag @photo.attachment.url %>
  <%= @photo.caption %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, id: 'editor' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
if ($.trumbowyg) {
        // Add imagur parameters to upload plugin
        $.extend(true, $.trumbowyg.upload, {
            serverPath: "<%= photos_url %>",
            fileFieldName: 'photo[attachment]',
            headers: {'Authorization': 'Client-ID 9e57cb1c4791cea'},
            urlPropertyName: 'photo_url'
        });
        }
$('#editor').trumbowyg({
            autogrow: true,
            fullscreenable: false,
            btnsDef: {
                // Customizables dropdowns
                image: {
                    dropdown: ['insertImage', 'upload', 'base64'],
                    ico: 'insertImage'
                }
            },
            btns: ['viewHTML',
                '|', 'formatting',
                '|', 'btnGrp-design',
                '|', 'link',
                '|', 'image',
                '|', 'btnGrp-justify',
                '|', 'btnGrp-lists',
                '|', 'horizontalRule']
        });
</script>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<body>
    <%= render partial: "layouts/navbar" %>
    <!-- Page Content -->
    <div class="container">
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Blog</h1>
            </div>
        </div>
        <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10">
            <p>We document all our trips on this page. Read about our adventures below!</p>
            <ul style="list-style: none;">
              <li>January 2015 - Xue Shan, 3886m.</li>
              <li>August 2014 - Rinjani, 3726m.</li>
              <li><%= link_to "12th August 2014 to 12th September 2014 - Mt. SUTD, 6056m", posts_path(tag: 'mountsutd2014') %></li>
              <li><%= link_to "22nd May 2014 to 28th May 2014 - Mt. SUTD Recce", posts_path(tag: 'indiarecce2014') %></li>
              <li><%= link_to "3rd May 2014 to 23rd May 2014 - Basic Alpine Mountaineering Course & Mt. Friendship, 5289m.",posts_path(tag: 'indiabamc2014') %></li>
              <li><%=link_to "6th January 2014 to 17th January 2014 - Ice Climbing & Mt. Dafeng, 5038m.",posts_path(tag: 'iceclimbing2014') %></li>
              <li>January 2013 - Mt. Kinabalu, 4095.2m.</li>
            </ul>
          </div>
          <div class="col-md-1"></div>
        </div>
        <!-- /.row -->
        <% @posts.each do |post| %>
          <div class="row" style="padding:10px">
              <div class="col-md-1"></div>
              <div class="col-md-3">
                  <div class="img-post-div">
                  <a href=<%= post_path(post.id) %>>
                    <img class="img-responsive img-hover" src=<%= get_first_image(post.content) %> alt="">
                  </a>
                  </div>
              </div>
              <div class="col-md-7">
                  <h3><%= link_to post.title, post %></h3>
                  <% post.tag_list.each do |tags| %>
                    <%= link_to posts_path(tag: tags) do %>
                      <span class="label label-default"><%= tags %></span>
                    <% end %>
                  <% end %>
                  <p><%= strip_tags(post.content).truncate(400, :separator => " ").html_safe %></p>
              </div>
              <div class="col-md-1"></div>
          </div>
        <% end %>
    </div>
</body>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6 post-class">
		<p>
		  <h2><%= @post.title %></h2>
      <% @post.tag_list.each do |tag| %>
        <span class="label label-default"><%= tag %></span>
      <% end %>
		  <h3><%= @post.name %></h3>
		</p>
		<p>
		  <%= @post.content %>
		</p>
		</div>
	<div class="col-md-3"></div>
</div>

app/views/static_pages/about.html.erb
<body class="body_pad">
    <!-- Page Content -->
    <div class="container">
        <!-- Intro Content -->
        <div class="row">
            <div class="col-md-6">
                <img class="img-responsive" src="assets/aboutus.jpg" alt="">
            </div>
            <div class="col-md-6">
                <h2>About SUTD Mountaineering</h2>
                <p>We started off in May 2012, when the pioneer batch of students matriculated. As pioneers of SUTD, we wanted to do something for the school and something we really loved. We gathered a group of individuals interested in mountaineering and founded SUTD Mountaineering. We began generating ideas on what we could do.</p>
                <p>Our initial idea was Mount Everest, but that proved to be very challenging and dangerous, as we had limited time. That idea was rejected, but we remained optimistic and began generating new ideas. Our new ideas were also rejected, and there wasn’t much progress.</p>
                <p>We tried our very best to keep the vision alive. Our perseverance paid off and we finally got an idea approved: To name a mountain after SUTD. We began raising funds and spreading awareness of what we were doing and we managed to raise funds for our club and other 5th Rows in SUTD.</p>
                <p>Since then, we have organized trips to regional mountains like Mount Rinjani, Indonesia, and Xue Shan, Taiwan. We are constantly seeking new adventures, so join us!</p>
                <p>In any case, the picture on the left wasn't from us. It was done by a professional photographer who shot for <a href="http://wearesutd.sutd.edu.sg">wearesutd</a>. Do check that out!</p>
            </div>
        </div>
        <!-- /.row -->

        <!-- Team Members -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Current EXCO</h2>
            </div>
            <div class="col-md-3 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="assets/junwen.jpg" alt="">
                    <div class="caption">
                        <h3>Loo Jun Wen<br>
                            <small>President</small>
                        </h3>
                        <p>Class of 2019. Freshmore.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="assets/vivian.jpg" alt="">
                    <div class="caption">
                        <h3>Vivian Lai<br>
                            <small>Treasurer</small>
                        </h3>
                        <p>Class of 2019. Freshmore.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="assets/jiewei.jpg" alt="">
                    <div class="caption">
                        <h3>Fung Jie Wei<br>
                            <small>Secretary</small>
                        </h3>
                        <p>Class of 2019. Freshmore.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="assets/javier.jpg" alt="">
                    <div class="caption">
                        <h3>Javier Su<br>
                            <small>Webmaster</small>
                        </h3>
                        <p>Class of 2015. Alumnus.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="assets/samuel.jpg" alt="">
                    <div class="caption">
                        <h3>Samuel Chin<br>
                            <small>Webmaster</small>
                        </h3>
                        <p>Class of 2015. Alumnus.</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <!-- Insert image of everyone who was in mountaineering -->
<!--         <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Our Community</h2>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
            </div>
        </div> -->
        <!-- /.row -->

        <hr>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

app/views/static_pages/expeditions.html.erb
<body class="body_pad">
	<%= render partial: "layouts/navbar" %>
    <!-- Page Content -->
    <div class="container">
        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-4 img-portfolio">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover" src="http://placehold.it/700x400" alt="">
                </a>
                <h3>
                    <a href="portfolio-item.html">Mount SUTD, Aug 2014</a>
                </h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
            <div class="col-md-4 img-portfolio">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover" src="http://placehold.it/700x400" alt="">
                </a>
                <h3>
                    <a href="portfolio-item.html">Friendship Peak, May 2014</a>
                </h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
            <div class="col-md-4 img-portfolio">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover" src="http://placehold.it/700x400" alt="">
                </a>
                <h3>
                    <a href="portfolio-item.html">China Ice Climbing, Jan 2014</a>
                </h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-4 img-portfolio">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover" src="http://placehold.it/700x400" alt="">
                </a>
                <h3>
                    <a href="portfolio-item.html">Mount Kinabalu, Jan 2013</a>
                </h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Pagination -->
        <!-- <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li>
                        <a href="#">&laquo;</a>
                    </li>
                    <li class="active">
                        <a href="#">1</a>
                    </li>
                    <li>
                        <a href="#">2</a>
                    </li>
                    <li>
                        <a href="#">3</a>
                    </li>
                    <li>
                        <a href="#">4</a>
                    </li>
                    <li>
                        <a href="#">5</a>
                    </li>
                    <li>
                        <a href="#">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div> -->
        <!-- /.row -->

        <hr>
    </div>
</body>

</html>

app/views/static_pages/fundraising.html.erb
<body class="body_pad">
  <div class="container">
    <div class="row">
		<h2>EASY BREAKFAST, WEEK 8 - WEEK 13</h2>
		<h3>When: Every Monday, Tuesday, Thursday</h3>
		<h3>Time: 8:30am - 9:00am</h3>
		<h3>Venue: Outside IDC</h3>
		<h3><a href="http://bit.ly/2eE7nvS">Order</a> before Sunday 12pm!</h3>
  	</div>
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <img class="img-responsive" src="assets/menu.png" alt="">
      </div>
      <div class="col-md-2"></div>
    </div>
</body>

app/views/static_pages/home.html.erb
<body>
    <!-- Header Carousel -->
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="fill" style="background-image:url('/assets/slideshow/slide1_cropped.jpg');"></div>
                <div class="carousel-caption">
                    <h2>Mount SUTD, 6056m</h2>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('/assets/slideshow/slide2_cropped.jpg');"></div>
                <div class="carousel-caption">
                    <h2>Basic Mountaineering Course, India</h2>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('/assets/slideshow/slide3.jpg');"></div>
                <div class="carousel-caption">
                    <h2>Ice Climbing, China</h2>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </header>

    <!-- Page Content -->
    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Welcome to SUTD Mountaineering
                </h1>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i>Our Expeditions</h4>
                    </div>
                    <div class="panel-body">
                        <p id="home_paragraph">Check out our blogs to find out about what trips we have been on!</p>
                        <!-- <a href=<%= posts_path %> class="btn btn-default">Learn More</a> -->
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"></i>Upcoming Trips</h4>
                    </div>
                    <div class="panel-body">
                        <p id="home_paragraph"><strong>Ice Climbing and Da Feng, China. 17th December 2016 - 26th December 2016.</strong></p>
                        <p id="home_paragraph"><strong>Ice Climbing and Da Feng, China. 7th January 2017 - 16th January 2017.</strong></p>
                        <!-- <a href="#" class="btn btn-default">Learn More</a> -->
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-compass"></i>Join us!</h4>
                    </div>
                    <div class="panel-body">
                        <p id="home_paragraph">Interested? Email us at mountaineering at club dot sutd dot edu dot sg.</p>
                        <!-- <a href="#" class="btn btn-default">Learn More</a> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

app/views/static_pages/roadmap.html.erb
<body class="body_pad">
  <div class="container">
    <div class="row">
      <h2>Academic Calendar</h2>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <table style="width:100%">
            <tr>
              <th></th>
              <th>January - April</th>
              <th>May - August</th> 
              <th>September - December</th>
            </tr>
            <tr>
              <th>2016</th>
              <td></td> 
              <td>Semester 1</td>
              <td>Semester 2</td>
            </tr>
            <tr>
              <th>2017</th>
              <td>Semester 3</td> 
              <td>Summer Break</td>
              <td>Semester 4</td>
            </tr>
            <tr>
              <th>2018</th>
              <td>Semester 5</td>
              <td>Summer Break</td>
              <td>Semester 6</td>
            </tr>
            <tr>
              <th>2019</th>
              <td>Semester 7</td> 
              <td>Semester 8</td>
            </tr>
          </table>
        </div>
        <div class="col-md-3"></div>
    </div>
    <div class="row">
      <h2>Training Phase</h2>
      <ul>
        <li>End of Semester 1 - Climb to regional mountain (Kinabalu, Rinjani, Fansipan, etc.)</li>
        <li>End of Semester 2 - Snow/Ice Climbing (Xueshan, Shuangqiaogou)</li>
        <li>End of Semester 3 - Basic Mountaineering Course (India)</li>
      </ul>
    </div>
    <div class="row">
      <h2>Development Phase</h2>
      <ul>
        <li>Summer Break - Organize your own trip with fellow mountaineeers or help guide the juniors.</li>
        <li>End of Semester 4 - Organize your own trip with fellow mountaineeers or help guide the juniors.</li>
        <li>End of Semester 5 - Organize your own trip with fellow mountaineeers or help guide the juniors.</li>
      </ul>
    </div>
    <div class="row">
      <h2>You're on your own!</h2>
      <ul>
        <li>Summer break - Start discussing which mountain you want to do with your fellow mountaineers as part of your graduation climb. Trying a 7000m mountain, or perhaps one of the Seven Summits, might be something you'd consider.</li>
      </ul>
    </div>
  </div>
</body>